version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: robin_qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  mongodb:
    image: mongo
    container_name: robin_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db